metar:
  filepath: "data/METAR/asos.csv"
  download-url: "http://mesonet.agron.iastate.edu/cgi-bin/request/asos.py?"
  api-url: "https://mesonet.agron.iastate.edu/api/1/"
  data-path: 'data/metar/'
map:
  data-path: 'data/map/'
database:
  technology: "postgresql"
  name: "database"
  username: "username"
  password: "password"
  host: "ground-db"
  port: 5432
station-data:
  filepath: "data/airports/airports.csv"
  download-url: "https://davidmegginson.github.io/ourairports-data/airports.csv"